# -*- coding: utf-8 -*-
"""text lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19isOkfVeqARMWn6Za4_7TdODv-xd06vF
"""

import re

# Зчитування тексту з файлу
with open('text1.txt', 'r', encoding='utf-8') as file:
    text = file.read()

print(text)
print()
def find_emails(text):
    # Регулярний вираз для пошуку електронних адрес
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

    # Знаходимо всі входження
    emails = re.findall(pattern, text)

    return emails
emails_from_text = find_emails(text)
print(emails_from_text)

def replace_non_letter_chars(text):
    # Регулярний вираз для знаходження електронних адрес
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

    # Функція для заміни символів у знайдених електронних адресах на "-"
    def replace_chars(match):
        return re.sub(r'[^A-Za-z0-9]', '-', match.group(0))

    # Заміна символів у знайдених електронних адресах
    modified_text = re.sub(pattern, replace_chars, text)

    return modified_text


modified_text = replace_non_letter_chars(text)

print("\n"+"Modified text:" +"\n"+ modified_text)

substring = text[0:20]
print(substring)
print(len(substring))
print(substring.count("t"))
print(substring.find("c"))
print(substring.index("three"))
print(substring.upper())
print(substring.lower())
print(substring.title())
print(substring.capitalize())
print("?".join(substring))
print(substring.isalnum())
print(substring.isalpha())
print(substring.isdigit())
print(substring.istitle())
print(substring.isspace())
print(substring.endswith('2'))
print(substring.startswith('A'))
print(substring.replace("12", "22"))
print(substring.split("o"))

import re

# Пошук за шаблоном
n = re.compile(r'(\d\d-)?\d\d')
substr= n.search('67-56-34')
print(substr)

n = re.compile(r'(\d\d)-(\d\d)-(\d\d)')
substr = n.search('I was already 67-56-34')
print('Str ' + substr.group())
print('Str0 ' + substr.group(0) )
print('Str1 ' +substr.group(1) )
print('Str2 ' +substr.group(2) )

n = re.compile(r'(\d\d)?\d\d')
substr = n.search('I was already 6-56-34')
print('StrOp ' + substr.group())

n = re.compile(r'(\d){2}')
substr = n.search('I was already 67-56-34')
print('Number ' + substr.group())
n = re.compile(r'(\d){1,4}')
substr = n.search('I was already 67-56-34')
print('Number ' + substr.group())

n = re.compile(r'[a-zA-Z0-9]')
substr = n.findall('I was already 67-56-34')
print(substr)


n = re.compile(r'was (\w)\w*')
# Заміна шаблону у рядку
substr = n.sub(r'****', "I was already67-56-34")
print(substr)

