# -*- coding: utf-8 -*-
"""text lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e5oiKW4vrLbXpw6LXiGqMg7tnGy2KxKx
"""

import nltk
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
#nltk.download('reuters')
from nltk.corpus import reuters
from nltk.probability import FreqDist
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tag import pos_tag

# 1.Зчитати файл text2. а) Порахувати кількість слів в останньому реченні
# (не враховуючи знаки пунктуації та інші спеціальні символи);
# б) позначити частини мови; в) знайти 9 слів, які зустрічаються найчастіше.

# 2.Використати корпус Reuters, четвертий текст категорії livestock.
# а) Вивести речення з другого до п’ятого;
# б) Вивести 10 прикметників, що зустрічаються найчастіше.
with open('text2.txt', 'r' ) as file:
  text = file.read()

sentences = sent_tokenize(text)
words = word_tokenize(text)

last_sentence = sentences[-1]
words_in_last_sentence = [word.strip('.,?!') for word in word_tokenize(last_sentence) if word.isalnum()]
num_words_in_last_sentence = len(words_in_last_sentence)
print(f"Кількість слів в останньому реченні: {num_words_in_last_sentence}")


# pos_tags = pos_tag(words)
# for word, pos_tag in pos_tags:
#   print(f"{word}: {pos_tag}")

fdist = FreqDist(words_in_last_sentence)
most_common_words = fdist.most_common(9)
print("9 слів, які зустрічаються найчастіше:")
for word, freq in most_common_words:
    print(f"{word}: {freq}")
print("--------------------------------------------------")
# Використати корпус Reuters, четвертий текст категорії livestock

livestock_fileids = reuters.fileids(categories='livestock')
fourth_livestock_fileid = livestock_fileids[3]
livestock_text = reuters.raw(fileids=fourth_livestock_fileid)


# print(livestock_text)

livestock_sentences = sent_tokenize(livestock_text)
livestock_words = word_tokenize(livestock_text)
for i in range(1, 4):  # ВСЬОГО 4!
    print(f"Речення {i+1}: {livestock_sentences[i]}")


livestock_pos_tags = pos_tag(livestock_words)
adjectives = [word for word, tag in livestock_pos_tags if tag.startswith('JJ')]
fdist_adj = FreqDist(adjectives)
most_common_adjectives = fdist_adj.most_common(10)
print("10 прикметників, що зустрічаються найчастіше:")
for adj, freq in most_common_adjectives:
    print(f"{adj}: {freq}")