[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
dotenv = { version = "0.15", optional = true }

[features]
default = []
standalone = ["dep:dotenv"]
